## Python version

In [1]:
from platform import python_version
print(python_version())

3.6.6


In [2]:
!pip install -q scipy==1.2

You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
!pip install -q statsmodels==0.9.0

You should consider upgrading via the 'pip install --upgrade pip' command.


In [4]:
!pip install -q xgboost

You should consider upgrading via the 'pip install --upgrade pip' command.


## Import Libraries

In [5]:
import numpy as np
from numpy.random import seed
seed(1)

import os
import csv
import random
import statsmodels.api as sm
import statsmodels.formula.api as smf
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

## Load Data

In [6]:
import boto3
import botocore
import pandas as pd
from sagemaker import get_execution_role

role = get_execution_role()

bucket = 'hotels770'
data_key_train = 'H1full.csv'
data_location_train = 's3://{}/{}'.format(bucket, data_key_train)

train_df = pd.read_csv(data_location_train)

In [7]:
a=train_df.head()
b=train_df
b
b.sort_values(['ArrivalDateYear','ArrivalDateWeekNumber'], ascending=True)

ID  IsCanceled  LeadTime  ArrivalDateYear ArrivalDateMonth  \
0          1           0       342             2015             July   
1          2           0       737             2015             July   
2          3           0         7             2015             July   
3          4           0        13             2015             July   
4          5           0        14             2015             July   
5          6           0        14             2015             July   
6          7           0         0             2015             July   
7          8           0         9             2015             July   
8          9           1        85             2015             July   
9         10           1        75             2015             July   
10        11           1        23             2015             July   
11        12           0        35             2015             July   
12        13           0        68             2015             July   
13        14           0        18             2015             July   
14        15           0        37             2015             July   
15        16           0        68             2015             July   
16        17           0        37             2015             July   
17        18           0        12             2015             July   
18        19           0         0             2015             July   
19        20           0         7             2015             July   
20        21           0        37             2015             July   
21        22           0        72             2015             July   
22        23           0        72             2015             July   
23        24           0        72             2015             July   
24        25           0       127             2015             July   
25        26           0        78             2015             July   
26        27           0        48             2015             July   
27        28           1        60             2015             July   
28        29           0        77             2015             July   
29        30           0        99             2015             July   
...      ...         ...       ...              ...              ...   
40021  40022           0        50             2017           August   
40022  40023           0        25             2017           August   
40024  40025           0        41             2017           August   
40025  40026           0       161             2017           August   
40026  40027           0       206             2017           August   
40027  40028           0       138             2017           August   
40028  40029           0        43             2017           August   
40029  40030           0       151             2017           August   
40030  40031           0       135             2017           August   
40031  40032           0       301             2017           August   
40032  40033           0        21             2017           August   
40034  40035           0       279             2017           August   
40035  40036           0        21             2017           August   
40036  40037           0       279             2017           August   
40038  40039           0       191             2017           August   
40039  40040           0       108             2017           August   
40040  40041           0       194             2017           August   
40041  40042           0       227             2017           August   
40042  40043           0       210             2017           August   
40043  40044           0       227             2017           August   
40047  40048           0       214             2017           August   
40048  40049           0       239             2017           August   
40049  40050           0       217             2017           August   
40050  40051           0       173             201

In [8]:
IsCanceled = train_df['IsCanceled']
y = IsCanceled

### Interval variables

In [9]:
leadtime = train_df['LeadTime']
arrivaldateyear = train_df['ArrivalDateYear']
arrivaldateweekno = train_df['ArrivalDateWeekNumber']
arrivaldatedayofmonth = train_df['ArrivalDateDayOfMonth']
staysweekendnights = train_df['StaysInWeekendNights']
staysweeknights = train_df['StaysInWeekNights']
adults = train_df['Adults']
children = train_df['Children']
babies = train_df['Babies']
isrepeatedguest = train_df['IsRepeatedGuest'] 
previouscancellations = train_df['PreviousCancellations']
previousbookingsnotcanceled = train_df['PreviousBookingsNotCanceled']
bookingchanges = train_df['BookingChanges']
agent = train_df['Agent']
company = train_df['Company']
dayswaitinglist = train_df['DaysInWaitingList']
adr = train_df['ADR']
rcps = train_df['RequiredCarParkingSpaces']
totalsqr = train_df['TotalOfSpecialRequests']

### Categorical variables

In [10]:
arrivaldatemonth = train_df.ArrivalDateMonth.astype("category").cat.codes
arrivaldatemonthcat=pd.Series(arrivaldatemonth)
mealcat=train_df.Meal.astype("category").cat.codes
mealcat=pd.Series(mealcat)
countrycat=train_df.Country.astype("category").cat.codes
countrycat=pd.Series(countrycat)
marketsegmentcat=train_df.MarketSegment.astype("category").cat.codes
marketsegmentcat=pd.Series(marketsegmentcat)
distributionchannelcat=train_df.DistributionChannel.astype("category").cat.codes
distributionchannelcat=pd.Series(distributionchannelcat)
reservedroomtypecat=train_df.ReservedRoomType.astype("category").cat.codes
reservedroomtypecat=pd.Series(reservedroomtypecat)
assignedroomtypecat=train_df.AssignedRoomType.astype("category").cat.codes
assignedroomtypecat=pd.Series(assignedroomtypecat)
deposittypecat=train_df.DepositType.astype("category").cat.codes
deposittypecat=pd.Series(deposittypecat)
customertypecat=train_df.CustomerType.astype("category").cat.codes
customertypecat=pd.Series(customertypecat)
reservationstatuscat=train_df.ReservationStatus.astype("category").cat.codes
reservationstatuscat=pd.Series(reservationstatuscat)

In [11]:
y1 = y
x1 = np.column_stack((leadtime,countrycat,marketsegmentcat,deposittypecat,customertypecat,rcps,arrivaldateyear,arrivaldatemonthcat,arrivaldateweekno,arrivaldatedayofmonth))
x1 = sm.add_constant(x1, prepend=True)

In [12]:
y1

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        1
9        1
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       1
28       0
29       0
        ..
40030    0
40031    0
40032    0
40033    0
40034    0
40035    0
40036    0
40037    0
40038    0
40039    0
40040    0
40041    0
40042    0
40043    0
40044    0
40045    0
40046    0
40047    0
40048    0
40049    0
40050    0
40051    0
40052    0
40053    0
40054    0
40055    0
40056    0
40057    0
40058    0
40059    0
Name: IsCanceled, Length: 40060, dtype: int64

In [13]:
x1

array([[  1., 342.,  95., ...,   5.,  27.,   1.],
       [  1., 737.,  95., ...,   5.,  27.,   1.],
       [  1.,   7.,  45., ...,   5.,  27.,   1.],
       ...,
       [  1., 204.,  55., ...,   1.,  35.,  29.],
       [  1., 211.,  45., ...,   1.,  35.,  31.],
       [  1., 161.,  33., ...,   1.,  35.,  31.]])

In [14]:
x_train, x_val, y_train, y_val = train_test_split(x1, y1, random_state=0)

## Boosting Technique: xgboost

### xgboost

In [15]:
# https://machinelearningmastery.com/xgboost-for-imbalanced-classification/

import xgboost as xgb
xgb_model = xgb.XGBClassifier(learning_rate=0.001,
                            max_depth = 1, 
                            n_estimators = 100,
                              scale_pos_weight=3)
xgb_model.fit(x_train, y_train)

print("Accuracy on training set: {:.3f}".format(xgb_model.score(x_train, y_train)))
print("Accuracy on validation set: {:.3f}".format(xgb_model.score(x_val, y_val)))

Accuracy on training set: 0.579
Accuracy on validation set: 0.571


### Predictions

In [16]:
xgb_predict=xgb_model.predict(x_val)
xgb_predict

array([1, 1, 1, ..., 0, 1, 1])

## Confusion Matrices

### xgboost

In [17]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_val,xgb_predict))
print(classification_report(y_val,xgb_predict))

[[3159 4107]
 [ 194 2555]]
              precision    recall  f1-score   support

           0       0.94      0.43      0.59      7266
           1       0.38      0.93      0.54      2749

    accuracy                           0.57     10015
   macro avg       0.66      0.68      0.57     10015
weighted avg       0.79      0.57      0.58     10015



In [18]:
data_key_test = 'H2full.csv'
data_location_test = 's3://{}/{}'.format(bucket, data_key_test)

h2data = pd.read_csv(data_location_test)

In [19]:
type(h2data)

pandas.core.frame.DataFrame

In [20]:
t_leadtime = h2data['LeadTime'] #1
t_arrivaldateyear = h2data['ArrivalDateYear']
t_arrivaldateweekno = h2data['ArrivalDateWeekNumber']
t_arrivaldatedayofmonth = h2data['ArrivalDateDayOfMonth']
t_staysweekendnights = h2data['StaysInWeekendNights'] #2
t_staysweeknights = h2data['StaysInWeekNights'] #3
t_adults = h2data['Adults'] #4
t_children = h2data['Children'] #5
t_babies = h2data['Babies'] #6
t_isrepeatedguest = h2data['IsRepeatedGuest'] #11
t_previouscancellations = h2data['PreviousCancellations'] #12
t_previousbookingsnotcanceled = h2data['PreviousBookingsNotCanceled'] #13
t_bookingchanges = h2data['BookingChanges'] #16
t_agent = h2data['Agent'] #18
t_company = h2data['Company'] #19
t_dayswaitinglist = h2data['DaysInWaitingList'] #20
t_adr = h2data['ADR'] #22
t_rcps = h2data['RequiredCarParkingSpaces'] #23
t_totalsqr = h2data['TotalOfSpecialRequests'] #24

In [21]:
t_arrivaldatemonth = h2data.ArrivalDateMonth.astype("category").cat.codes
t_arrivaldatemonthcat = pd.Series(t_arrivaldatemonth)
t_mealcat=h2data.Meal.astype("category").cat.codes
t_mealcat=pd.Series(t_mealcat)
t_countrycat=h2data.Country.astype("category").cat.codes
t_countrycat=pd.Series(t_countrycat)
t_marketsegmentcat=h2data.MarketSegment.astype("category").cat.codes
t_marketsegmentcat=pd.Series(t_marketsegmentcat)
t_distributionchannelcat=h2data.DistributionChannel.astype("category").cat.codes
t_distributionchannelcat=pd.Series(t_distributionchannelcat)
t_reservedroomtypecat=h2data.ReservedRoomType.astype("category").cat.codes
t_reservedroomtypecat=pd.Series(t_reservedroomtypecat)
t_assignedroomtypecat=h2data.AssignedRoomType.astype("category").cat.codes
t_assignedroomtypecat=pd.Series(t_assignedroomtypecat)
t_deposittypecat=h2data.DepositType.astype("category").cat.codes
t_deposittypecat=pd.Series(t_deposittypecat)
t_customertypecat=h2data.CustomerType.astype("category").cat.codes
t_customertypecat=pd.Series(t_customertypecat)
t_reservationstatuscat=h2data.ReservationStatus.astype("category").cat.codes
t_reservationstatuscat=pd.Series(t_reservationstatuscat)

In [22]:
a = np.column_stack((t_leadtime,t_countrycat,t_marketsegmentcat,t_deposittypecat,t_customertypecat,t_rcps,t_arrivaldateyear,t_arrivaldatemonthcat,t_arrivaldateweekno,t_arrivaldatedayofmonth))
a = sm.add_constant(a, prepend=True)
IsCanceled = h2data['IsCanceled']
b = IsCanceled
b=b.values

In [23]:
prh2 = xgb_model.predict(a)
prh2

array([0, 1, 1, ..., 1, 1, 1])

In [24]:
type(prh2)

numpy.ndarray

In [25]:
x=prh2[1:1000]
x

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [26]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(b,prh2))
print(classification_report(b,prh2))

[[12650 33578]
 [ 1972 31130]]
              precision    recall  f1-score   support

           0       0.87      0.27      0.42     46228
           1       0.48      0.94      0.64     33102

    accuracy                           0.55     79330
   macro avg       0.67      0.61      0.53     79330
weighted avg       0.70      0.55      0.51     79330

