# Import Libraries

In [1]:
import os
import csv
import random
import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.preprocessing import MinMaxScaler

/home/michael/anaconda3/lib/python3.6/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


# Data Cleaning

In [2]:
train_df = pd.read_csv('H1full.csv')
a=train_df.head()
b=train_df
b
b.sort_values(['ArrivalDateYear','ArrivalDateWeekNumber'], ascending=True)

IsCanceled  LeadTime  ArrivalDateYear ArrivalDateMonth  \
0               0       342             2015             July   
1               0       737             2015             July   
2               0         7             2015             July   
3               0        13             2015             July   
4               0        14             2015             July   
...           ...       ...              ...              ...   
40055           0       212             2017           August   
40056           0       169             2017           August   
40057           0       204             2017           August   
40058           0       211             2017           August   
40059           0       161             2017           August   

       ArrivalDateWeekNumber  ArrivalDateDayOfMonth  StaysInWeekendNights  \
0                         27                      1                     0   
1                         27                      1                     0   
2                         27                      1                     0   
3                         27                      1                     0   
4                         27                      1                     0   
...                      ...                    ...                   ...   
40055                     35                     31                     2   
40056                     35                     30                     2   
40057                     35                     29                     4   
40058                     35                     31                     4   
40059                     35                     31                     4   

       StaysInWeekNights  Adults  Children  ...      DepositType        Agent  \
0                      0       2         0  ...  No Deposit              NULL   
1                      0       2         0  ...  No Deposit              NULL   
2                      1       1         0  ...  No Deposit              NULL   
3                      1       1         0  ...  No Deposit               304   
4                      2       2         0  ...  No Deposit               240   
...                  ...     ...       ...  ...              ...          ...   
40055                  8       2         1  ...  No Deposit               143   
40056                  9       2         0  ...  No Deposit               250   
40057                 10       2         0  ...  No Deposit               250   
40058                 10       2         0  ...  No Deposit                40   
40059                 10       2         0  ...  No Deposit                69   

           Company DaysInWaitingList     CustomerType     ADR  \
0             NULL                 0        Transient    0.00   
1             NULL                 0        Transient    0.00   
2             NULL                 0        Transient   75.00   
3             NULL                 0        Transient   75.00   
4             NULL                 0        Transient   98.00   
...            ...               ...              ...     ...   
40055         NULL                 0        Transient   89.75   
40056         NULL                 0  Transient-Party  202.27   
40057         NULL                 0        Transient  153.57   
40058         NULL                 0         Contract  112.80   
40059         NULL                 0        Transient   99.06   

       RequiredCarParkingSpaces  TotalOfSpecialRequests ReservationStatus  \
0                             0                       0         Check-Out   
1                             0                       0         Check-Out   
2                             0                       0         Check-Out   
3                             0                       0         Check-Out   
4                             0                       1         Check-Out   
...                         ...                     ...               ...   
40055   

In [3]:
IsCanceled = train_df['IsCanceled']
y = IsCanceled

In [4]:
# Interval Variables
leadtime = train_df['LeadTime']
arrivaldateyear = train_df['ArrivalDateYear']
arrivaldateweekno = train_df['ArrivalDateWeekNumber']
arrivaldatedayofmonth = train_df['ArrivalDateDayOfMonth']
staysweekendnights = train_df['StaysInWeekendNights']
staysweeknights = train_df['StaysInWeekNights']
adults = train_df['Adults']
children = train_df['Children']
babies = train_df['Babies']
isrepeatedguest = train_df['IsRepeatedGuest'] 
previouscancellations = train_df['PreviousCancellations']
previousbookingsnotcanceled = train_df['PreviousBookingsNotCanceled']
bookingchanges = train_df['BookingChanges']
agent = train_df['Agent']
company = train_df['Company']
dayswaitinglist = train_df['DaysInWaitingList']
adr = train_df['ADR']
rcps = train_df['RequiredCarParkingSpaces']
totalsqr = train_df['TotalOfSpecialRequests']

In [5]:
# Categorical variables
arrivaldatemonth = train_df.ArrivalDateMonth.astype("category").cat.codes
arrivaldatemonthcat=pd.Series(arrivaldatemonth)
mealcat=train_df.Meal.astype("category").cat.codes
mealcat=pd.Series(mealcat)
countrycat=train_df.Country.astype("category").cat.codes
countrycat=pd.Series(countrycat)
marketsegmentcat=train_df.MarketSegment.astype("category").cat.codes
marketsegmentcat=pd.Series(marketsegmentcat)
distributionchannelcat=train_df.DistributionChannel.astype("category").cat.codes
distributionchannelcat=pd.Series(distributionchannelcat)
reservedroomtypecat=train_df.ReservedRoomType.astype("category").cat.codes
reservedroomtypecat=pd.Series(reservedroomtypecat)
assignedroomtypecat=train_df.AssignedRoomType.astype("category").cat.codes
assignedroomtypecat=pd.Series(assignedroomtypecat)
deposittypecat=train_df.DepositType.astype("category").cat.codes
deposittypecat=pd.Series(deposittypecat)
customertypecat=train_df.CustomerType.astype("category").cat.codes
customertypecat=pd.Series(customertypecat)
reservationstatuscat=train_df.ReservationStatus.astype("category").cat.codes
reservationstatuscat=pd.Series(reservationstatuscat)

# Feature Selection: only interval variables are considered for this purpose

In [6]:
x = np.column_stack((leadtime,arrivaldateyear,arrivaldatemonthcat,arrivaldateweekno,arrivaldatedayofmonth,staysweekendnights,staysweeknights,adults,children,babies,mealcat,countrycat,marketsegmentcat,distributionchannelcat,isrepeatedguest,previouscancellations,previousbookingsnotcanceled,reservedroomtypecat,assignedroomtypecat,bookingchanges,deposittypecat,dayswaitinglist,customertypecat,adr,rcps,totalsqr,reservationstatuscat))
x = sm.add_constant(x, prepend=True)

In [7]:
x_interval = np.column_stack((leadtime,arrivaldateyear,arrivaldateweekno,arrivaldatedayofmonth,staysweekendnights,staysweeknights,adults,children,babies,isrepeatedguest,previouscancellations,previousbookingsnotcanceled,bookingchanges,dayswaitinglist,adr,rcps,totalsqr))
x_interval = sm.add_constant(x_interval, prepend=True)

## Univariate Selection with fclassif (Interval)

In [8]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from numpy import set_printoptions

# feature extraction
test1 = SelectKBest(score_func=f_classif, k=6)
fit = test1.fit(x_interval, y)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(x_interval)
# summarize selected features
print(features[0:5,:])

[     nan 2226.02    76.377   18.699    3.529  248.82   248.233  261.578
  266.099   21.672  434.29   529.067  237.465  535.306   52.856  484.488
 2532.85   415.28 ]
[[342.   0.   0.   3.   0.   0.]
 [737.   0.   0.   4.   0.   0.]
 [  7.   0.   0.   0.  75.   0.]
 [ 13.   0.   0.   0.  75.   0.]
 [ 14.   0.   0.   0.  98.   0.]]


/home/michael/.local/lib/python3.6/site-packages/sklearn/feature_selection/_univariate_selection.py:114: UserWarning: Features [0] are constant.
  UserWarning)
/home/michael/.local/lib/python3.6/site-packages/sklearn/feature_selection/_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
